name: Auto Merge Release PR

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  auto-merge:
    if: startsWith(github.head_ref, 'release/v') && github.event.pull_request.labels[0].name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "release"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000" 