name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commits } = await github.rest.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'v0.0.0',
              head: context.sha
            });
            
            const changelog = commits.commits.map(commit => {
              return `- ${commit.commit.message} (${commit.sha.substring(0, 7)})`;
            }).join('\n');
            
            return changelog;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## What's Changed
            
            ${{ steps.changelog.outputs.result }}
            
            ## Installation
            
            ```bash
            npm install @next-live/nextlive@${{ steps.get_version.outputs.VERSION }}
            # or
            yarn add @next-live/nextlive@${{ steps.get_version.outputs.VERSION }}
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 