name: Update Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update Changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): {version}'
          preset: 'angular'
          tag-prefix: 'v'
          output-file: 'CHANGELOG.md'
          skip-version-file: 'true'
          skip-commit: 'false'
          skip-tag: 'false'
          release-count: 0
          release-type: 'major'
          package-name: '@next-live/nextlive'
          package-files: 'package.json'
          package-type: 'npm'
          package-path: '.'
          package-version: ${{ steps.get_version.outputs.VERSION }} 